name = "sharex-r2-cloudflare-workers"
type = "javascript"
account_id = "f1307d32ef6e901ab1f027a47c3e646c"
workers_dev = true
route = "cdn.joshua.wales/*"
zone_id = "66c67048116214d406bed3a542359a81"
compatibility_date = "2022-04-22"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[[r2_buckets]]
bucket_name = "sharex-files"
binding = "R2_BUCKET"
